### ISSUE TITLE
JWT Token

### ISSUE THREAD

**Issue by CVillemus** [NZXTCorp/web-integrations-examples#1]
Hello there,

I'm wondering what do I have to put on JWT Token ? For the Spotify integration For now i've tryed blank and random text.
I've installed everything, but got a "INVALID_CLIENT: Invalid redirect URI" message after I've logged with my spotify account.
Also tried to create new project,  and update client ID and stuff. Not working, tryed to clear cookies and retry, install / uninstall etc.

Any Idea ?

Btw: It's a wonderfull project you've worked on :) Thanks a lot

**Comment by CVillemus** [comment]
> 

From what I understood it's auto generated bu the libs ? is it

**Comment by robbieplata** [comment]
@CVillemus The JWT Secret should be a long random string to ensure the integrity of the tokens. 

The callback should be `<your-url>/api/auth/callback/spotify`
