### ISSUE TITLE
youtube integration not looping

### ISSUE THREAD

**Issue by tfm4th** [NZXTCorp/web-integrations-examples#11]
Video doesn't loop in the example or when you replace the YouTube link. It looks like the example script in there isn't using the variables within the script and the base YouTube URL is a full URL instead.

**Comment by iesaasse1** [comment]
only work from here 

https://cam-redirect.nzxt.com/action/load-web-integration?url=https://brunoandradebr.github.io/nzxt/

**Comment by robbieplata** [comment]
Halting support for this web integration
