### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by washhtubs** [NZXTCorp/web-integrations-examples#4]
Hi,

I've installed all of the required programs and have followed the setup instructions, but every time I click "Continue with Spotify", I get a message saying "Unable to log in.
 You will be redirected to the home page. If you are not redirected, click here", which just takes me back to the "Continue with Spotify" page.

In the terminal I get the error message:

[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error client_id is required {
  error: {
    message: 'client_id is required',
    stack: 'TypeError: client_id is required\n'

,even though I've put my client ID in the correct places. I've tried a fresh install of the program as well as new Spotify client and secret ID's and can't get it to work unfortunately. Any help would be appreciated :)

**Comment by stoneG** [comment]
Hi @washhtubs, can you share where you've added the client_id? e.g. what does your env file look like? Make sure to redact your actual data.

**Comment by washhtubs** [comment]
Hi, I've added the client_id into the .env.local file ("C:\. . .\Documents\NZXT Web Integrations\web-integrations-examples-main\web-integrations-examples-main\spotify-album-art\.env.local.txt") which I'm fairly certain is in the right directory, correct me if I'm wrong though.

The actual file with ID's censored reads:

JWT_SECRET=XXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NEXTAUTH_URL=http://localhost:3000
SPOTIFY_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SPOTIFY_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by stoneG** [comment]
@washhtubs the file needs to be named `.env.local` not `spotify-album-art.env.local.txt` - try that?

**Comment by washhtubs** [comment]
The file is called `.env.local`, not sure why the file path didn't say that.

I've tried all the steps again and am still getting the same message.

**Comment by olsenben** [comment]
open cmd, navigate to your directory (cd <your directory>) and create the .env.local file by entering ‘notepad .env.local' another window will open in notepad and you can input your variables there. I had the same issue in that I had just made a .txt file and this fixed it by creating a LOCAL file instead of a Text document. Hope that helps!

**Comment by washhtubs** [comment]
@olsenben That worked (I think), thank you very much. Although, now it's saying "INVALID_CLIENT: Invalid redirect URI" when I try to sign in through NZXT Cam.

**Comment by olsenben** [comment]
@washhtubs What is your redirect URI in your spotify app? I believe I had this issue as well. When you visit your settings in your Spotify app in your developer account, your website should be whatever your local host is (ex http://localhost:3000) and your redirect should be http://[yourlocalhost]/api/auth/callback/spotify (ex http://localhost:3000/api/auth/callback/spotify). I originally had the redirect set to my local host and that was not working, it must have the callback.
